### ISSUE TITLE
Redirect back to originating sign in origin

### ISSUE THREAD

**Issue by fool** [netlify/gotrue#102]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

Once git-gateway is successfully set up on a site using Identity, it seems to block login via google

**- If the current behavior is a bug, please provide the steps to reproduce.**

- setup git-gateway as a backend for netlify CMS
- observe that email login still works
- observe that previously working github login doesn't work (nor does google)

**- What is the expected behavior?**

- all account types could work for login

**- Please mention your Go version, and operating system version.**

Netlify's built-in identity service.  More details for the Netlify team in https://app.intercom.io/a/apps/q245f50x/respond/inbox/conversation/11684625129

**Comment by fool** [comment]
cc @calavera as requested.  Asked the affected customer to fill in some additional details if possible :)

**Comment by DirtyF** [comment]
Thanks @fool, what kind of details should I provide?

FWIW here is what happens when I try to login:
![netlify-identity](https://user-images.githubusercontent.com/103008/30509859-15d830f8-9aba-11e7-9a98-3664b1dafd3d.gif)

Could it be a token issue?

**Comment by brycekahle** [comment]
@DirtyF Part of the problem does seem to be you are not redirected back to `/admin`, where the widget can process the tokens. Was it redirecting properly before you setup git-gateway?

**Comment by brycekahle** [comment]
I think the root issue is that the widget is hosted at `/admin` but we redirect back to `/` by default (emails will use `/` by default too). Unfortunately, we don't expose the configuration setting to change that redirect URL in the UI yet.

I think the default for external providers could be more intelligent and attempt to redirect you back to where you were (unless overridden by the config setting).

**Comment by DirtyF** [comment]
@brycekahle Yes, it was redirecting properly before I setup git-gateway.

**Comment by tech4him1** [comment]
> I think the default for external providers could be more intelligent and attempt to redirect you back to where you were (unless overridden by the config setting).

I think this makes a lot of sense, and if done correctly would fix https://github.com/netlify/netlify-identity-widget/issues/86 as well.
