### ISSUE TITLE
cannot use pageParams.Offset() (type uint64) storage/sql/storage.go:115:35

### ISSUE THREAD

**Issue by sebastianmacias** [netlify/gotrue#105]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**

When running **go run main.go:**

I'm getting the following error:
```shell
dev@DevX:[~/go/src/bitbucket.org/project/micro/auth/vendor/github.com/netlify/gotrue]: go run main.go 
# bitbucket.org/project/micro/auth/vendor/github.com/netlify/gotrue/storage/sql
storage/sql/storage.go:115:35: cannot use pageParams.Offset() (type uint64) as type int in argument to q.Offset
storage/sql/storage.go:115:55: cannot use pageParams.PerPage (type uint64) as type int in argument to q.Offset(pageParams.Offset()).Limit

```
**- If the current behavior is a bug, please provide the steps to reproduce.**

* cd into my-path-to/github.com/netlify/gotrue
* go run main.go

**- What is the expected behavior?**
Microservice should start

**- Please mention your Go version, and operating system version.**
Go 1.9, Ubuntu 16.04

Thanks

**Comment by brycekahle** [comment]
Do you get the same build failure with Go 1.8.3?

**Comment by sebastianmacias** [comment]
@brycekahle  I will try it with 1.8.3 and let you know

**Comment by sebastianmacias** [comment]
This error doesn't happen with go 1.8.3 however this one does: https://github.com/netlify/gotrue/issues/106

**Comment by dorelljames** [comment]
Oddly, I get the error #106 even at go version 1.8.3.

**Comment by brycekahle** [comment]
Closing due to solution in #106
