### ISSUE TITLE
add facebook login

### ISSUE THREAD

**Issue by fool** [netlify/gotrue#107]
**- Do you want to request a *feature* or report a *bug*?**

*feature*

**- What is the current behavior?**

*login providers limited to google + git providers*

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

*login providers includes facebook*

**- Please mention your Go version, and operating system version.**

n/a

**Comment by sebastianmacias** [comment]
Even better, a bridge use any of the [goth](https://github.com/markbates/goth) providers would be very helpful.

**Comment by calavera** [comment]
@sebastianmacias feel free to open a new issue to discus moving to Goth. Right now it's not a priority for us, but I think it's still worth considering given that Goth is more mature than our internal providers. Unfortunately, your comment will be lost in time when #111 is merged.

**Comment by sebastianmacias** [comment]
Thanks for the heads up @calavera I will open the issue once this gets closed.

**Comment by cfjedimaster** [comment]
Sorry to comment on an old bug. I came here looking to see if FB can be used with Netlify Identity. When I posted on the forums I was told it wasn't implemented here yet, but then I see that a PR was merged 3 years. So if it _is_ supported here, how do I use it in Netlify Identity?
