### ISSUE TITLE
Password recovery does not confirm email

### ISSUE THREAD

**Issue by sogen** [netlify/gotrue#113]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Added email manually, I even clicked the reset password from my email, got the "Email not confirmed" message
**- If the current behavior is a bug, please provide the steps to reproduce.**
Reset password,
Update password
Login
Logout
Login
Enter credentials
![screen shot 2017-10-04 at 5 31 09 pm](https://user-images.githubusercontent.com/2784323/31204679-14168b2e-a92a-11e7-92db-54efff01c4ef.png)

**- What is the expected behavior?**
Mail works
**- Please mention your Go version, and operating system version.**
OSX Sierra

**Comment by brycekahle** [comment]
It appears you sent a password recovery email before confirming your email. It would make sense for password recovery to also confirm an email, so I believe that is the bug here.
