### ISSUE TITLE
Feature Request: Please support goth auth providers

### ISSUE THREAD

**Issue by sebastianmacias** [netlify/gotrue#122]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
Not supported

**- If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**- What is the expected behavior?**
Support [goth](https://github.com/markbates/goth) auth providers

**- Please mention your Go version, and operating system version.**
N/A

[goth](https://github.com/markbates/goth) currently offers support to 40 different providers, instead of/in addition to writing providers individually i.e. bitbucket, github, gitlab, and google I highly recommend developing a "bridge" so any of the providers offered by [goth](https://github.com/markbates/goth) can be used with gotrue.

I am staring to use gotrue in some projects and it would make things a lot easier/more flexible if goth's providers were available in gotrue.

Here is a integration example I found: https://github.com/kataras/iris/blob/fc2cc6048113f1eea8f82cd9b442c736f60ed48d/_examples/authentication/oauth2/main.go

Maybe it could be used as a starting point.

Thanks,

Seb

**Comment by hubgit** [comment]
It would be useful to at least have a generic way to add identity providers that are OpenID Connect compliant, where in theory it's enough to fetch the discovery document from `.well-known/openid-configuration` and obtain the rest of the configuration from there.

**Comment by HintikkaKimmo** [comment]
Is there any news around this. I've wanted to use Netlify as the more flexible landing page provider, but FB login is an absolute must for marketing operations (twitter is nice to have...). Is there a generic way to add providers or instructions how to use something like Auth0?

**Comment by rybit** [comment]
For the time being this is not on any internal roadmaps. I'd like to see it done, but we don't have the bandwidth to implement it right now. We would consider/review/etc PRs around this, but won't be able to do it in the near future.
