### ISSUE TITLE
.netlify/identity/settings returns a 404

### ISSUE THREAD

**Issue by futuregerald** [netlify/gotrue#125]
For some sites (I can't find a way to replicate this, or any correlation between sites it happens on), `.netlify/identity/settings` returns `{code":404,"msg":"Unable to locate site configuration"}` instead of the identity settings that are supposed to be loaded. Deleting the identity instance and enabling it again does not reliably make the problem go away, however the problem can go away eventually. I just don't know what causes it or what fixes it. @bcomnes has experienced this, and a user also reported it:

https://app.intercom.io/a/apps/q245f50x/respond/inbox/1479299/conversations/12840437723

In that case above, the issue was no longer evident the next day, and there were no changes made to the site.

**Comment by futuregerald** [comment]
Also experienced by https://app.intercom.io/a/apps/q245f50x/respond/inbox/unassigned/conversations/13505491085

**Comment by bcomnes** [comment]
I'll make sure to add this to the upcoming roadmap.

**Comment by sindregusdal** [comment]
Same problem. Happend twice using the one-click-hugo version

**Comment by futuregerald** [comment]
@sindregusdal contact us in support so we can look in to it.

**Comment by brycekahle** [comment]
I think this has to due with the CDN caching the 404 for way too long. This may be an issue with the headers the API is returning on the 404

**Comment by calavera** [comment]
This was fixed already.

**Comment by mifi** [comment]
Still an issue

**Comment by chrispwolf** [comment]
Also seeing this issue now. Trying to set up a Gatsby site with Netlify CMS and Itentify and I can't move forward.

**Comment by imjamesku** [comment]
I'm also having this issue

**Comment by rrufus** [comment]
Also seeing this issue.

**Comment by sasilver75** [comment]
Having this issue as well

**Comment by rrufus** [comment]
I found that, using github, if I:
- Remove git gateway from the identity settings
- Delete identity from my app
- re-add the github repo to the netlify site configuration (build and deploy -> edit settings)
- Wait for it to redeploy
- Re-enable identity
- Re-add git gateway
- Wait 30 minutes

It seemed to work.

**Comment by kkarkos** [comment]
When defining the Identity URL in your code make sure you using:

```https://xxx-xxx.netlify.app````

**only** and not

```https://xxx-xxx.netlify.app/.netlify/identity````

Otherwise this will try load the settings from ```/.netlify/identity/.netlify/identity/settings``` and result in a 404.
