### ISSUE TITLE
Provide method for our customer to discover the "signed-up-and-sent-confirmation-email" state for someone signing in through 3rd party provider in their site code.

### ISSUE THREAD

**Issue by fool** [netlify/gotrue#146]
**- Do you want to request a *feature* or report a *bug*?**

*feature*

**- What is the current behavior?**

*currently there is no way to programatically tell after the signup widget has returned to the specified post-signup location, that there is a pending confirmation email, so the site code can prompt the site visitor to do something about it (e.g. go click a confirmation link)

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

*customers would like to see some status they can check easily via code that could run on their site + potentially a Lambda function call"

**- Please mention your Go version, and operating system version.**

netlify hosted gotrue for customer # 2 who uses it.

**Comment by calavera** [comment]
You can get that information from the user object we send in the response after signing up, or fetching the user with the /admin/user endpoint.

Pseudo-JS example:

```js
user = JSON.parse(response.data)
if (!user["confirmed_at"] && user["confirmation_sent_at"]) {
  alert("We've sent you a confirmation email, go click the confirmation link")
}
```
