### ISSUE TITLE
Document EXTERNAL_REDIRECT_URL

### ISSUE THREAD

**Issue by hubgit** [netlify/gotrue#154]
The variable `EXTERNAL_REDIRECT_URL` should (unless I'm missing something) be added to the [External Authentication Providers](https://github.com/netlify/gotrue#external-authentication-providers) section of the README, as it's needed for setting the URL that receives the hash after authenticating with an external provider via `/authorize`.

**Comment by brycekahle** [comment]
It is missing from the documentation, but it is not required by default. We attempt to be intelligent and use referrer headers to try and redirect the user back to where they came from. If the value is set, it would override that behavior and use the static value.

**Comment by hubgit** [comment]
I've found out why the automatic "redirect to referrer" wasn't working as expected - there was a mismatch between the referrer domain ("localhost") and the domain in the `SITE_URL` variable ("127.0.0.1"), so the referrer was being ignored. Now I've made those consistent, the  `EXTERNAL_REDIRECT_URL` variable doesn't need to be set.
