### ISSUE TITLE
Allow a user to remain signed in on other devices?

### ISSUE THREAD

**Issue by hubgit** [netlify/gotrue#156]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

When an authenticated user makes a request to `/logout`, all the refresh tokens for that user are deleted.

**- What is the desired behavior?**

When an authenticated user makes a request to `/logout` including a  refresh token, delete only this refresh token, so the user can stay signed in on other devices.

**Comment by calavera** [comment]
I think it's a fair assumption to only delete the token that you're currently using to logout.

**Comment by calavera** [comment]
After thinking about this. I think our current behavior is more correct, so I'm going to close this.
