### ISSUE TITLE
Delete user metadata

### ISSUE THREAD

**Issue by cameronmcefee** [netlify/gotrue#168]
This may be a feature request, if it doesn't already exist. How do I delete arbitrary user data that I've previously attached? I can overwrite it by submitting new data with matching keys, but submitting the value as `undefined` (similar to React state's method) didn't do anything and by design empty keys don't do anything.

**Comment by WiteCastle** [comment]
Do you have custom metadata for your user? If so, how did you do that?

**Comment by AlexVipond** [comment]
I'm in need of this feature too!
