### ISSUE TITLE
Delete a user - feature request

### ISSUE THREAD

**Issue by pukhalski** [netlify/gotrue#174]
Dear Netlify team,
is there a way to delete a user account (by user itself or admin)?

If not, any ETA on this?

Thank you.

**Comment by rybit** [comment]
This looks to exist already: https://github.com/netlify/gotrue/blob/feb3c89564b573e306119a83b918f2e76c91a9a0/api/admin.go#L226-L250

That looks like it is under the path `/admin/users/{user_id}`
