### ISSUE TITLE
Replace package satori/go.uuid

### ISSUE THREAD

**Issue by josselin-c** [netlify/gotrue#178]
This issue has been opened automaticaly because we think you are using satori/uuid in your code. Unfortunately, satori/uuid has a critical defect where it doesn't generate random UUIDV4s satori/go.uuid#73  and should be replaced as the maintainer has been unresponsive for 5 months with the bug still open. Alternative packages you should consider: https://github.com/google/uuid https://github.com/pborman/uuid

**Comment by k1ng440** [comment]
Solved.

**Comment by rybit** [comment]
So this isn't actually solved. The package (https://github.com/gobuffalo/uuid) we moved to is a fork of the problematic package and archived. 

![image](https://user-images.githubusercontent.com/406376/47238591-8cc45680-d397-11e8-8a92-2ddc40386a60.png)

**Comment by hfte** [comment]
https://github.com/gobuffalo/uuid has removed the .Equal function. I can't compile the current master source, because seems like all mentained uuid versions are incompatible. Or which are you using?

**Comment by trestoa** [comment]
According to https://github.com/satori/go.uuid/issues/90#issuecomment-447887426, https://github.com/gofrs/uuid is the permanent and maintained fork of the module. I was already able to build and run gotrue using this module. I will do some more testing and submit a PR if everything works correctly.
