### ISSUE TITLE
Public docker build?

### ISSUE THREAD

**Issue by ernsheong** [netlify/gotrue#179]
Will there be a public docker build for `gotrue`?

**Comment by edevil** [comment]
Yes, why not publish the image in Netlify's docker hub repository?

**Comment by fodkastir** [comment]
@edevil I got this error as well.

**Comment by fodkastir** [comment]
@edevil If you change the first line of Dockerfile to FROM golang:1.11.3-alpine as build, you can build the image successfully.

**Comment by edevil** [comment]
@fodkastir Well, somehow the hash matches if I use 1.11.3 but then the build breaks due to https://github.com/netlify/gotrue/pull/188#issuecomment-435651982:

```
api/provider/saml.go:225:5: undefined: "github.com/gobuffalo/uuid".Equal
```

:)

**Comment by indeed-yen** [comment]
@edevil  try this https://github.com/netlify/gotrue/pull/188#issuecomment-435651982

**Comment by tooolbox** [comment]
@biilmann what do you think?  :)
