### ISSUE TITLE
Fix `gotrue migrate`

### ISSUE THREAD

**Issue by grinkus** [netlify/gotrue#182]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When running `gotrue migrate` on a fresh docker instance (with `mysql:5.7`) it exits with:

```
DEBU[2018-08-31T21:37:00.283202945Z] Set log level to: debug                      
INFO[2018-08-31T21:37:00.283456644Z] Reading migrations from /usr/local/etc/gotrue/migrations 
INFO[2018-08-31T21:37:00.28450867Z] before status                                
[POP] 2018/08/31 21:37:00 CREATE TABLE schema_migration (
version VARCHAR (255) NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX version_idx ON schema_migration (version);
FATA[2018-08-31T21:37:00.289102913Z] Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE UNIQUE INDEX version_idx ON schema_migration (version)' at line 4
github.com/netlify/gotrue/vendor/github.com/gobuffalo/pop.(*Connection).timeFunc
	/go/src/github.com/netlify/gotrue/vendor/github.com/gobuffalo/pop/connection.go:184
github.com/netlify/gotrue/vendor/github.com/gobuffalo/pop.(*Query).Exec
	/go/src/github.com/netlify/gotrue/vendor/github.com/gobuffalo/pop/executors.go:19
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
On a fresh docker instance run `gotrue migrate`.

**- What is the expected behavior?**
DB is successfully inited.

**- Please mention your Go version, and operating system version.**
Linux 25ffb6af1032 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 Linux
golang:1.9.2
As specified in the [Dockerfile](https://github.com/netlify/gotrue/blob/master/Dockerfile)

**Comment by k1ng440** [comment]
I am running into the same problem.

**Comment by k1ng440** [comment]
https://github.com/netlify/gotrue/pull/188

**Comment by k1ng440** [comment]
This issue has been solved. Please close it.
