### ISSUE TITLE
Stripe subscription charge  fail webhook: access to user db to update user data [CRITICAL]

### ISSUE THREAD

**Issue by pukhalski** [netlify/gotrue#183]
**- Do you want to request a *feature* or report a *bug*?**
Feature.

**- What is the current behavior?**
If Stripe subscription charge fails, user receives an email (set up in Stripe Dashboard) about it, but there's also a possibility to push an event from Stripe to webhook. These webhook should update user data accordingly but there's no ability to access user db (no token or identity).

**- What is the expected behavior?**
Provide access to manipulate users from webhooks with static app token/secret or any other mechanism.

**Comment by Auspicus** [comment]
@pukhalski 

Using the context parameter you should be able to access a short lived "app token":

```javascript
exports.handler = (event, context) => {
  const { identity } = context.clientContext;
  const API_TOKEN = identity.token;
  const API_ENDPOINT = identity.url;
  // ... use token
}
```

**Comment by pukhalski** [comment]
@biilmann I am setting up a webhook from Stripe to a function, so Stripe is going to trigger it without any token, of course.

@Auspicus, thanks, I will take a look!

**Comment by elucidsoft** [comment]
This does not work.   Using the method @Auspicus referred to if you call the identity /user endpoint, pass in the short lived jwt token the response back is "Could not read user Claim ID".

**Comment by pukhalski** [comment]
Any updates on this one?

**Comment by corford** [comment]
One nice way to do this might be to introduce an "app token" concept? An app token could have either read, write or read/write access to the app meta data of all users. Like a refresh token, it never expires and can only be revoked. The db table to contain these tokens would have a similar schema to the `refresh_tokens` table (with addition of a grant column to specify capabilities of each issued token).

GoTrue could then expose admin API endpoints to allow listing, creation, revocation and capability setting (r,w,r/w) of app tokens (or alternatively this could be done via the cli?).

Finally, GoTrue would then need to expose an API endpoint to allow updating and deleting app meta data attributes for a given user (using the presented app token for authorisation).

Above would allow you to e.g. create a scoped app token for the Stripe webhook that could update or set a new attribute for the affected user (...i think? I have no experience using stripe or their webhooks and don't know how configurable they are).

**Comment by Auspicus** [comment]
You need to use the admin API ie. /admin not /user. You can see docs on that here: https://github.com/netlify/gotrue-js#admin-methods

**Comment by Auspicus** [comment]
I agree though that having a way to access the Identity API in contexts outside of their platform would be great because it's virtually impossible to E2E test without running via Netlify Functions.
