### ISSUE TITLE
Add oauth1

### ISSUE THREAD

**Issue by k1ng440** [netlify/gotrue#189]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
no auth1. twitter, tumblr and dropbox

i will work on adding oauth1 as soon as my current pull request merged. 

i will probbly use following packages. 
* https://github.com/dghubble/oauth1
* https://github.com/dghubble/gologin
* https://github.com/mrjones/oauth

**Comment by k1ng440** [comment]
Greetings @bcomnes and @rybit,

Please give me your thoughts on those packages

**Comment by rybit** [comment]
I was thinking using goth (https://github.com/markbates/goth) would be a good solution.

**Comment by k1ng440** [comment]
I agree.

**Comment by k1ng440** [comment]
well i tried to use goth but i can't figure out how to Integrate rewriting the API.ExternalProviderRedirect() and API.ExternalProviderCallback()
