### ISSUE TITLE
What is the GOTRUE_SITE_URL? is it gotrue server URL or gocommerce server URL ?

### ISSUE THREAD

**Issue by goodforever** [netlify/gotrue#192]
Hi all, 
     What is the GOTRUE_SITE_URL?   is it  gotrue server URL or  gocommerce server URL ?

**Comment by SimplyCodin** [comment]
The enviroment variable `GOTRUE_SITE_URL` is the url gotrue listen to.
GoCommerce is not related to GoTrue

**Comment by mraerino** [comment]
Have a look at the docs: https://github.com/netlify/gotrue#top-level
It should be clear from that.
