### ISSUE TITLE
Confirm email URL is error 

### ISSUE THREAD

**Issue by goodforever** [netlify/gotrue#195]
- Do you want to request a *feature* or report a *bug*?
bug

- What is the current behavior?
After I signed up, I got  confirm email with link (http://localhost:9999/verify#confirmation_token=HD7AQaGFHWaVdsPEZ3d88Q)
(I set GOTRUE_MAILER_URLPATHS_CONFIRMATION=/verify)

- If the current behavior is a bug, please provide the steps to reproduce.
 I click this email , I got "HTTP ERROR 405"
- What is the expected behavior?
I think the link URL is error , 

- Please mention your Go version, and operating system version.
go version go1.10.3 darwin/amd64

**Comment by bboyz269** [comment]
The documentation is really lacking. But from the README, my guess is that you have to implement the confirmation link by yourself.
In which you need to make a POST request to `/verify` with payload of
```
{
    "type": "signup",
    "token": "HD7AQaGFHWaVdsPEZ3d88Q"
}
```

**Comment by goodforever** [comment]
@bboyz269 thanks!
