### ISSUE TITLE
allow disabling of the "email-changed-reconfirm-your-new-address" email from the UI

### ISSUE THREAD

**Issue by fool** [netlify/gotrue#196]
$customer points out that in Identity settings, "Allow users to sign up without verifying their email address"  (e.g. here: https://app.netlify.com/sites/picked/settings/identity#confirmation-template and hit Edit) means they never get a confirmation mail there, but that there is not a similar "disable" setting for the "changed email address" template here:  https://app.netlify.com/sites/picked/settings/identity#email-change-template .  

He suggests that the two settings should be in sync, or at least, settable to be in sync.

I suspect this is one that needs API work, and is maybe WONTFIX since it is so edge-casey and besides, confirming your email address is only smart particularly upon change, but I promised to raise the very low priority issue.

**Comment by bcomnes** [comment]
Moved
