### ISSUE TITLE
Security issue in GoTrue README ?

### ISSUE THREAD

**Issue by corford** [netlify/gotrue#201]
I'm still learning/playing with GoTrue so apologies if I'm mistaken but... the project README seems to contain what looks like a dangerous example for the `PUT /user` endpoint:

```javascript
{
  "email": "new-email@example.com",
  "password": "new-password",
  "data": {
    "key": "value",
    "number": 10,
    "admin": false
  }
}
```

Above example contains an `admin` attrib but according to https://www.netlify.com/blog/2018/03/29/jamstack-architecture-on-netlify-how-identity-and-functions-work-together/#adding-identity : "Each user in Netlify Identity has user_metadata and app_metadata attributes. The user_metadata can be updated by the user directly through the identity API, but the app_metadata can only be updated by an admin user."

So the example code above seems to suggest a user could escalate their app privs by issuing a simple `PUT` request ? To avoid this, shouldn't the `admin` attrib be stored in the user's `app_metadata` ?

Related:  does GoTrue have any sanity checks/limits in place to deal with a malicious user trying to DoS the system by setting a huge user_metadata payload ?

**Comment by futuregerald** [comment]
Hi @corford ,

Users can update their `user_metadata` from the frontend, but they can't update their `app_metadata`. We use roles inside of app_metadata, and that's where you should put anything privileged. You can only change the `app_metadata` if you have an admin jwt token already.

**Comment by corford** [comment]
Thanks @futuregerald  but that's exactly what I'm saying. The example for the `PUT /user` endpoint in the README is showing a user adding meta data themselves. They could just as easily set `"admin"= true` no?

**Comment by futuregerald** [comment]
No. While they can update their user_metadata, that information isn't used to determine user roles. You can put anything in the json body of the user_metadata. roles are in `app_metadata.authorization.roles` array. Users can't update the app_metadata so they can't set an admin role. Even if they put admin in the `user_metadata` it won't give them any additional access.

**Comment by corford** [comment]
Sorry, I get that. I assumed the `"admin"` attribute in the example was just an attrib (that happened to be called admin) sent by the user e.g to be used by the app for something.

Basically, I'm not saying it opens a security issue for GoTrue but I am saying if an app developer decides to reference an attrib called `admin` from the `user_metadata` then this is unsafe as the user themselves can change that attrib at will.

Just seemed strange to include an `"admin"` attrib in the example code that's all.

**Comment by futuregerald** [comment]
That's not an attribute that we specify, just an example of what someone could send. It's up to the dev to decide what to set in the user_metadata. We don't specify what needs to be in there.

**Comment by corford** [comment]
Ok right. So in the example, instead of `"admin": true` maybe `"marketing_opt_in": true` or something is safer? Better than inadvertently giving devs (who haven't realized or properly understood that `user_metdata` is user modifiable) a bad idea to copy.

**Comment by corford** [comment]
Anyway, it's fairly minor. In my case it confused me for a second because the README is very light on info about how to modify `app_metadata` and interact with GoTrue as an admin in general.

Are there any plans to document admin API endpoints or CLI commands etc. a bit better (for folks looking to leverage GoTrue as a self hosted thing and not necessarily rely on AWS/netlify functions)?

**Comment by c3controls** [comment]
I second @corford on this, would be great to have more thorough documentation of API endpoints & CLI commands. Currently it is suggested to backwards engineer endpoints using browser dev tools in the Netlify dashboard...

Also, I would like to repeat **corford's** question above regarding DoS/big payloads:

> ...does GoTrue have any sanity checks/limits in place to deal with a malicious user trying to DoS the system by setting a huge user_metadata payload ?

I'll open a new issue if this deserves more than a comment. Thanks!!

**Comment by skllpr** [comment]
I absolutely agree that there should be documentation. There needs to be a significant increase in examples of how to run the API in Netlify Functions, without functions, and on client side.
