### ISSUE TITLE
Not able to log in or reset password

### ISSUE THREAD

**Issue by RymaTech** [netlify/gotrue#208]
**- Do you want to request a *feature* or report a *bug*?**
Bug.
**- What is the current behavior?**

1. I click on the github login button. 

2. "Invalid authorization code"
     "This login link is no longer valid. To request a new link, enter the email you used to sign up."

3. I type in my email address. 

4. I receive an email asking me to reset my password.

"Forgot your password?
No worries. Let’s get you to your account settings so you can choose a new one."

I am not sure I ever set a password, but I am never given opportunity to enter it anyhow. 

5. I click the reset password button within the email anyhow and it takes me to "https://app.netlify.com/account/settings" but nothing appears except for the logo spinning round and round endlessly. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
See above
**- What is the expected behavior?**
Not sure, I just want to access my Netlify account.

**- Please mention your Go version, and operating system version.**

I am using a macbook

**Comment by overlordofmu** [comment]
@RymaTech , I want to make sure this isn't something login/account specific as opposed to an issue with this library itself. Would you be willing to please email support@netlify.com to open a support case with us for this?

**Comment by jmrowczynski** [comment]
Hi RymaTech. Did you resolve your problem? Same happened to me.

**Comment by divyats6550** [comment]
Same happened with me....Anybody know how to resolve?

**Comment by erikhm91** [comment]
I have the same issue now, also wondering.

**Comment by jmrowczynski** [comment]
I suggest you to describe that situation in email and send it to support. It worked for me. Problem was fixed by them

**Comment by divyats6550** [comment]
> I suggest you to describe that situation in email and send it to support. It worked for me. Problem was fixed by them

Thanks.....Did the same.....Problem happened because the login for my email address was marked as a spam account by their automated systems.They Reactivated the account and its working now...

**Comment by rybit** [comment]
Glad this was resolved
