### ISSUE TITLE
Inconsistent Update User Metadata API

### ISSUE THREAD

**Issue by smuriu** [netlify/gotrue#213]
For updates to user metadata, the **user** api expects input with the key `data`.
https://github.com/netlify/gotrue/blob/738272dd6983b5993d8be8b8e9c78a37162c94c8/api/user.go#L17

For updates to user metadata, the **admin** api expects input with the key `user_metadata`.
https://github.com/netlify/gotrue/blob/738272dd6983b5993d8be8b8e9c78a37162c94c8/api/admin.go#L20

The user model will return `user_metadata`.
https://github.com/netlify/gotrue/blob/738272dd6983b5993d8be8b8e9c78a37162c94c8/models/user.go#L45

Perhaps we should adopt a uniform reference to user metadata. `user_metadata` is less ambiguous/more descriptive than just `data` especially considering that there is also an `app_metadata` field in this api too.

**Comment by smuriu** [comment]
Also see issue #166

**Comment by sw-yx** [comment]
thank you. i'm not the maintainer of this but i think a PR to fix this would be welcome.

**Comment by mraerino** [comment]
we would need to have a solution that would not involve a breaking change. we cannot simply deprecate the `data` field as it is used by a lot of people.
