### ISSUE TITLE
Add Microsoft as an external provider

### ISSUE THREAD

**Issue by JamieMagee** [netlify/gotrue#216]
**- Do you want to request a *feature* or report a *bug*?**

A feature. An addition to the list of supported providers

**- What is the current behavior?**

Current providers are very developer-centric

**- What is the expected behavior?**

Implement Microsoft as an external provider, using the [golang.org/x/oauth2/microsoft](https://godoc.org/golang.org/x/oauth2/microsoft) package.

**Comment by JamieMagee** [comment]
Still relevant. Open PR waiting for review for 1+ year.

**Comment by ranjithrd** [comment]
https://github.com/supabase/gotrue seems to be a better managed version of GoTrue with support for more social auth providers

**Comment by JamieMagee** [comment]
True, but I opened a PR to add this functionality a year and a half ago that is currently waiting for review.
