### ISSUE TITLE
rate limit invalid login attempts to protect against brute force attacks.

### ISSUE THREAD

**Issue by fool** [netlify/gotrue#224]
**- Do you want to request a *feature* or report a *bug*?**

- feature

**- What is the current behavior?**

- currently, you can attempt to guess a password for a known login repeatedly without any change in system behavior.

**- If the current behavior is a bug, please provide the steps to reproduce.**

- attempt to login with a wrong password dozens of times in a row.

**- What is the expected behavior?**

- it would be harder to brute force a password guessing attack on an account.

**- Please mention your Go version, and operating system version.**

N/A

**Comment by fool** [comment]
this unmerged/closed PR has some work in that area:  https://github.com/netlify/gotrue/pull/104

**Comment by laurajodz** [comment]
Just noticed this issue isn't on a GH project - feel free to icebox! :)

**Comment by fool** [comment]
I think that Pod C owns gotrue based on [this spreadsheet](https://docs.google.com/spreadsheets/d/1tKI01wZJQMZ_aA0mYIjvGlUdodrr5LJ6eA1ns_beE34/edit?pli=1#gid=789384474&fvid=382600715), so putting it in that project

**Comment by kaganjd** [comment]
closed with https://github.com/netlify/bitballoon/issues/6099
