### ISSUE TITLE
Use OpenID Connect for external identity providers

### ISSUE THREAD

**Issue by CrowdHailer** [netlify/gotrue#236]
Previously raised as a feature request on the forum.
https://community.netlify.com/t/use-openid-connect-for-external-identity-providers/10777

*copied below*

The list of external identity providers is limited to BitBucket, GitLab, GitHub and Google.
As I understand it these integrations worth through OAuth 2.0.

We have a client who would like to identify users on a netlify hosted site using [DID.app](https://did.app).
([DID.app](https://did.app) is an Identity provider that focuses on passwordless authentication, disclaimer I am one of the founders there)

At this stage [DID.app](https://did.app) is a very small service, obviously not the best candidate for next specific OAuth integration. However we follow the OpenID Connect specification (as I believe the 4 providers you already support do as well)

The OpenID Connect specification includes discovery of all the relevant configuration such as token endpoints. Therefore the only additional information that needs to be specified when setting up on netlify is the url of the provide.

By supporting setting up external identity providers using OpenID Connect, a customer should be able to use any identity provider.

**Comment by aaronpk** [comment]
well did.app didn't last very long, but it would still be great to support arbitrary OpenID Connect providers!

**Comment by johndpope** [comment]
those are supported with supabase fork.
