### ISSUE TITLE
How to Use gotrue with Hugo?

### ISSUE THREAD

**Issue by goldcoders** [netlify/gotrue#253]
I would love to learn how i can implement gotrue with Hugo framework

Do u have any examples?

**Comment by ElouanL** [comment]
Hi,
Well, as long as I remembered hugo generate a website running without rendering server. Gotrue is made to protect a server side ressource. So, why do you want to use them together ?

**Comment by goldcoders** [comment]
i just remember because i wanna use supabase as my backend, they use gotrue for authentication as well
