### ISSUE TITLE
Sending password as query param

### ISSUE THREAD

**Issue by awalias** [netlify/gotrue#255]
Guys loving the work so far!

**- Do you want to request a *feature* or report a *bug*?**
bug / security improvement

**- What is the current behavior?**
as per the README `/token` endpoint expects email and password as query params
<img width="851" alt="image" src="https://user-images.githubusercontent.com/458736/87389295-13dc4800-c5d9-11ea-9798-a94203740707.png">
but this is not secure, would be better to send in the body of the request

**- If the current behavior is a bug, please provide the steps to reproduce.**
try to send these `username` and `password` fields in the body of the request, but gotrue complains that there is no user that matches this email

**- What is the expected behavior?**
should be able to send via request body instead of in URI

**- Please mention your Go version, and operating system version.**
Ubuntu 18.04.4 LTS. go1.13.5

**Comment by awalias** [comment]
also I don't know if the choice of `username` as parameter was deliberate, but it is a mismatch with the `email` field used in the signup endpoint and in the db schema

**Comment by awalias** [comment]
fyi the changes I made on the supabase fork above allow the sending of email and password values in body as json. I realized by looking at gotrue-js that you are actually sending the values in the body but in query format. This change adds some flexibility

**Comment by suciuvlad** [comment]
+1. Curious about this one too. Any reason why the data is sent as `application/x-www-form-urlencoded` ?

**Comment by hydroid7** [comment]
That's simply the [OAuth2 Password Grant](https://www.oauth.com/oauth2-servers/access-tokens/password-grant/). Nothing special.
