### ISSUE TITLE
Adding Issuer to the JWT Tokens

### ISSUE THREAD

**Issue by hydroid7** [netlify/gotrue#271]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
Generated JWT token contains no issuer claim.

**- Expected**
Generated JWT contains an issuer claim.

I'd be able to contribute the simple solution described below:

1. Adding configuration variable `GOTRUE_JWT_ISS=XXX`
2. Extending the function which generates the jwt.

**Comment by AhmedJeylani** [comment]
I would also look to push this aswell. Is this something that has been implemented yet? 
This is quite an important feature for my team.

**Comment by chrisbra-riftpay** [comment]
Would like to bump this, would be a good feature for my team to use aswell
