### ISSUE TITLE
sqlite backend

### ISSUE THREAD

**Issue by raboof** [netlify/gotrue#279]
For small-scale/development deployments it would be a great feature if GoTrue supported sqlite as a backend next to mysql - or can you recommend another OAuth2/JWT server for such scenario's?

**Comment by jrapoport** [comment]
@raboof  just fyi: https://github.com/jrapoport/gothic started off as a fork, but has since been completely written and includes sqlite support.

**Comment by jrapoport** [comment]
@raboof just fyi: https://github.com/jrapoport/gothic started off as a fork, but has since been completely rewritten and includes sqlite support.

**Comment by ashleyconnor** [comment]
>just fyi: https://github.com/jrapoport/gothic started off as a fork, but has since been completely rewritten and includes sqlite support.

Is there a good reason why issues are closed on this repo?

**Comment by jrapoport** [comment]
> Is there a good reason why issues are closed on this repo?

I guess they were off by default and i never noticed. 🤷‍♂️ On now.
