### ISSUE TITLE
Where can i Deploy gotrue?

### ISSUE THREAD

**Issue by goldcoders** [netlify/gotrue#281]
Any Recommendation where i can deploy gotrue?

**Comment by codeplus254** [comment]
> Any Recommendation where i can deploy gotrue?

You can deploy gotrue on any linux servers. If the question was for what reason? Personally, I couple it with netlifycms to manage users who can edit my public site. Happy coding!

**Comment by goldcoders** [comment]
I mean what cloud hosting do you think, or can recommend best suit
