### ISSUE TITLE
[FEATURE] Authentication providers

### ISSUE THREAD

**Issue by calavera** [netlify/gotrue#29]
**- Do you want to request a *feature* or report a *bug*?**

This is a new feature.

**- What is the current behavior?**

Currently, Gotrue only allows people to signup/logic via email / password.

**- What is the expected behavior?**

We should allow people to configure Gotrue with several authentication providers, like GitHub, GitLab and Bitbucket.

This should be configured globally, and it's probably related to #16.

**Comment by brycekahle** [comment]
Fixed via #34
