### ISSUE TITLE
[FEATURE] Admin API

### ISSUE THREAD

**Issue by calavera** [netlify/gotrue#30]
**- Do you want to request a *feature* or report a *bug*?**

This is a new feature.

**- What is the current behavior?**

There is no automatic way to manage users, tokens and roles.

**- What is the expected behavior?**

We want to have an API for machine users to manage users, tokens, roles and audiences.

This API should be able to:

- Create users for a given audience with a given role.
- Remove users from an audience.
- Modify a user's role in an audience.
- List users per audience.

Only machine users with a global "superadmin"(or something similar) role should be able to access this api.

**Comment by rybit** [comment]
One issue here is that we should have an admin role that is scoped to an audience. 

For instance, we need a way to say that I am admin for the "smashing" audience, but just a user for the "netlify" audience. 

We will still need to have a "superadmin"-esque role. 

The other thing I am thinking of is can an admin delete their audience?

**Comment by brycekahle** [comment]
Fixed via #33
