### ISSUE TITLE
Testing site

### ISSUE THREAD

**Issue by calavera** [netlify/gotrue#32]
We should have a testing site, or a way to boot a site that uses GoTrue to validate that we don't break current features and new features work as expected.

**Comment by andrioid** [comment]
Demo or screen shots would also help indicate how the mature the project is. Looks interesting so far.

**Comment by bcomnes** [comment]
@calavera this seems covered by https://identity.netlify.com.  Optimistically closing.  Feel free to re-open if there is more to do here.
