### ISSUE TITLE
Runbook Update

### ISSUE THREAD

**Issue by lexicondevil** [netlify/gotrue#353]
> Note: This is issue is part of the [Service Transfer Project](https://www.notion.so/netlify/Service-and-On-Call-Transfer-Plan-ad56ae285c264dad8c8718305e4063ff). The goal is to ensure project documentation is up to date and help the receiving team understand what the service does and how to maintain and operate it. The previous team is primarily responsible for doing this work, and the receiving team is the stakeholder on this issue and has final approval.
> 
> These are a set of guidelines, not a rigid set of requirements. If the receiving team already has expertise on this service and is comfortable operating it, they may complete whatever subset of the tasks they find appropriate and close this issue.
> 
> The assignees on this issue are intended to be "manager of previous team" and "manager of new team" based on what's in the [Service Ownership Spreadsheet](https://docs.google.com/spreadsheets/d/1mwEZ6kkQfP_DVZWlsOK2DgOn96nMOH8pMmZFwqqBLNA/). If these are incorrect please update the assignees on this issue and update the spreadsheet to match.

### Runbook Update

Make sure there’s an operations runbook for the service that meets these criteria:

- [ ]  Service runbooks should be created under the “Specific Services” section of the [Infra Runbooks](https://www.notion.so/Infra-Runbooks-f3af11d3d3764553906ebd98736c6b26) page in Notion. (You don't need to move existing runbooks here, but if you're creating a new runbook this would be a good place to put it.)
- [ ]  Link to the runbook from first section of service README
- [ ]  Links to dashboards
- [ ]  Instructions on how to deploy, how to hotfix, how to roll back a deploy
- [ ]  Descriptions of common issues and how to triage whether or not it is occurring
- [ ]  Some monitors may need a specific response from the on-call engineer. In that case there should be a dedicated section in the runbook for that process, and the monitor should link to that section.

Link to the service's runbook here so the receiving team can review.

**Examples:**
[Envelope runbook](https://www.notion.so/Envelope-runbook-1a7a884f01b442a0a75f9ff171aee42a)
[Functions Origin Runbook](https://www.notion.so/Functions-Origin-Runbook-2451c36fc73c4c49ad888d41c82ccb62) 

**Further reading:**
[https://www.pagerduty.com/resources/learn/what-is-a-runbook/](https://www.pagerduty.com/resources/learn/what-is-a-runbook/)
[https://www.transposit.com/devops-blog/itsm/what-makes-a-good-runbook/](https://www.transposit.com/devops-blog/itsm/what-makes-a-good-runbook/)

**Comment by rybit** [comment]
This is an public repo. I'm going to close this for now.
