### ISSUE TITLE
Ability to invite a user

### ISSUE THREAD

**Issue by rybit** [netlify/gotrue#43]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
n/a

**- What is the expected behavior?**
When triggered one user (admin level) should be able to invite a new user. We would then send them an email with a signup link that would generate a JWT for them. It would be up to the client to then enforce things like setting up a password.

![](https://www.cutestpaw.com/wp-content/uploads/2011/11/Hamburger.jpg)

**Comment by brycekahle** [comment]
I think it might be simpler to enforce the client passes along a password when redeeming the verification token.

So instead of the normal signup flow:
signup(email+password)->verify email->redeem(token)->JWT

Invites become:
invite(email)->invite email->redeem(token+password)->JWT

Thoughts?

**Comment by rybit** [comment]
sounds good to me. I am always a fan of more security.
