### ISSUE TITLE
ability to control registration style

### ISSUE THREAD

**Issue by rybit** [netlify/gotrue#49]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
n/a 

**- What is the expected behavior?**
The ability to set registration to be 

- open - anyone can signup
- request - you can ask to signup
- invite only - only private links

![](http://cdn.skim.gs/image/upload/v1456341719/msi/bernese_smzzpp.jpg)

**Comment by calavera** [comment]
I'm wondering how this affects the signup workflow. Can people still signup and will be marked as pending for approval? is sign up disabled if you choose invite only? can administrators send invites at this point?

/cc @biilmann, @brycekahle

**Comment by calavera** [comment]
this is done.
