### ISSUE TITLE
Mailer settings cannot be rolled back after setting

### ISSUE THREAD

**Issue by calavera** [netlify/gotrue#71]
**- Do you want to request a *feature* or report a *bug*?**

This is a bug.

**- What is the current behavior?**

After settings subjects or templates, there is no way to unset them.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create an instance with mailer settings
2. Try unsetting one of the subjects to use the default.

**- What is the expected behavior?**

We should remove the setting and use the default values.

**Comment by brycekahle** [comment]
Hmm. This is how `mergo` works, it does not overwrite if you use the zero value. We don't have a way to know the difference between not sent and empty string.

This is why I initially wanted only full config updates, instead of partial, to avoid issues like this.

**Comment by calavera** [comment]
yup, I'm thinking about the best way to solve this.

**Comment by calavera** [comment]
fixed by #75
